### ISSUE TITLE
Check two arrays are equal or not

### ISSUE THREAD

**Issue by anomekumar08** [anomekumar08/python-cpp-projects#12]
Hey ! Please help me with this issue. You can solve it with python or cpp then you need to make a pull request.

Given two arrays A and B of equal size N, the task is to find if given arrays are equal or not. Two arrays are said to be equal if both of them contain same set of elements, arrangements (or permutation) of elements may be different though.
Note : If there are repetitions, then counts of repeated elements must also be same for two array to be equal.

Example 1:

Input:
N = 5
A[ ] = {1,2,5,4,0}
B[ ] = {2,4,5,0,1}
Output: 1
Explanation: Both the array can be 
rearranged to {0,1,2,4,5}
Example 2:

Input:
N = 3
A[ ] = {1,2,5}
B[ ] = {2,4,15}
Output: 0
Explanation: A[] and B[] have only 
one common value.

**Comment by sudheerdagar** [comment]
Please assign this task to me and also add hactoberfest label.

**Comment by Anant2961** [comment]
Hey @anomekumar08 , Please assign this task to me I Will create a PR ASAP for this issue

**Comment by Anant2961** [comment]
Done Kindly Check the PR
