### ISSUE TITLE
Spirally traversing a matrix (python or cpp only)

### ISSUE THREAD

**Issue by anomekumar08** [anomekumar08/python-cpp-projects#30]
Given a matrix of size r*c. Traverse the matrix in spiral form.

Example 1:

Input:
r = 4, c = 4
matrix[][] = {{1, 2, 3, 4},
           {5, 6, 7, 8},
           {9, 10, 11, 12},
           {13, 14, 15,16}}
Output: 
1 2 3 4 8 12 16 15 14 13 9 5 6 7 11 10

**Comment by mb-008** [comment]
kindly assign this to me

**Comment by manav-06** [comment]
@anomekumar08 you can assign this to me

**Comment by robert1745** [comment]
@anomekumar08  pls assign this task to me.

**Comment by Devesh-coder** [comment]
@anomekumar08 Do you want a solution in Java?

**Comment by anomekumar08** [comment]
> @anomekumar08 Do you want a solution in Java?

No , Thanks! @Devesh-coder

**Comment by jay13makhija** [comment]
Please assign me this issue and merge my pull request

**Comment by jay13makhija** [comment]
Please accept my PR.
