### ISSUE TITLE
Merge Two Sorted Lists 

### ISSUE THREAD

**Issue by anomekumar08** [anomekumar08/python-cpp-projects#4]
Hey ! Help me with this issue and create Pull request. You can use Python or cpp for this issue.
You are given the heads of two sorted linked lists list1 and list2.

Merge the two lists in a one sorted list. The list should be made by splicing together the nodes of the first two lists.

Return the head of the merged linked list.

 
Example 1:

Input: list1 = [1,2,4], list2 = [1,3,4]
Output: [1,1,2,3,4,4]

Example 2:

Input: list1 = [], list2 = []
Output: [ ]

Example 3:
Input: list1 = [], list2 = [0]
Output: [0]
 

Constraints:
 # The number of nodes in both lists is in the range [0, 50].
#  -100 <= Node.val <= 100
#  Both list1 and list2 are sorted in non-decreasing order.

**Comment by prabhleenn** [comment]
Hello, please assign me this issue.

**Comment by RitoDas1923** [comment]
I have submitted a PR . Please check it once.
