### ISSUE TITLE
Want to add Hangman Game in Python (Python Project)

### ISSUE THREAD

**Issue by SubratYeeshu** [anomekumar08/python-cpp-projects#47]
Please assign it to me under hacktoberfest 2022 tag

**Comment by SubratYeeshu** [comment]
@anomekumar08

**Comment by anomekumar08** [comment]
Please create a quality issue and work on some good project.

**Comment by SubratYeeshu** [comment]
please generate some more issues in the issue panel for hacktoberfest

**Comment by SubratYeeshu** [comment]
like can you give example

**Comment by SubratYeeshu** [comment]
will leetcode question works?

**Comment by SubratYeeshu** [comment]
@anomekumar08

**Comment by SubratYeeshu** [comment]
ok

**Comment by anomekumar08** [comment]
Bro! the reason i am not accepting you pr is mainy becoz there are many repo which has been excluded from hacktober fest . They are only approving repo which have quality projects..
