### ISSUE TITLE
Median of Two Sorted Arrays (cpp or python)

### ISSUE THREAD

**Issue by SubratYeeshu** [anomekumar08/python-cpp-projects#56]
Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.
The overall run time complexity should be O(log (m+n)).

Input: nums1 = [1,3], nums2 = [2]
Output: 2.00000
Explanation: merged array = [1,2,3] and median is 2.

@anomekumar08 Please assign it to me under HF22

**Comment by RohitShah1706** [comment]
@anomekumar08 
Please assign this issue to me.

**Comment by SubratYeeshu** [comment]
Please merge my PR for this issue
